[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "appledb_common"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.95"
entity = { path = "../entity" }
serde = "1.0.217"
serde_json = "1.0.138"
serde_norway = "0.9.42"
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.43.0", features = ["fs"] }
url = "2.5.4"
utoipa = { version = "5.3.1", features = ["axum_extras"] }
